module.exports = {
  "status": [
    {
      id: 0,
      label: "To analyze",
      color: "orange lighten-5",
      textColor: "orange--text text--lighten-5",
      contrastColor: "deep-orange darken-4",
      contrastTextColor: "deep-orange--text text--darken-4",
      icon: "mdi-help-circle-outline",
    },
    {
      id: 1,
      label: "To test",
      color: "orange lighten-2",
      textColor: "orange--text text--lighten-2",
      contrastColor: "white",
      contrastTextColor: "white--text",
      icon: "mdi-flask-empty-outline",
    },
    {
      id: 2,
      label: "Dropped",
      color: "grey lighten-4",
      textColor: "grey--text text--darken-1",
      contrastColor: "grey",
      contrastTextColor: "grey--text",
      icon: "mdi-minus-circle-outline",
    },
    {
      id: 3,
      label: "To implement",
      color: "deep-orange lighten-2",
      textColor: "deep-orange--text text--lighten-2",
      contrastColor: "white",
      contrastTextColor: "white--text",
      icon: "mdi-shovel",
    },
    {
      id: 4,
      label: "Implemented",
      color: "green lighten-5",
      textColor: "green--text text--lighten-5",
      contrastColor: "green darken-4",
      contrastTextColor: "green--text text--darken-4",
      icon: "mdi-thumb-up-outline",
    },
    {
      id: 5,
      label: "Usefull later",
      color: "purple lighten-5",
      textColor: "purple--text text--lighten-5",
      contrastColor: "purple darken-5",
      contrastTextColor: "purple--text text--darken-5",
      icon: "mdi-clock",
    }
  ],
  "repositoryPerPage": 50,
}